### ISSUE TITLE
`npm run` on multiple transactions

### ISSUE THREAD

**Issue by mwakaba2** [forta-protocol/forta-agent-sdk#115]
Hi there! Would it be possible to run `npm run` on more than one transaction?

I created an agent that'll emit an alert based on a series of transactions. I have several transactions that I'd like to test that are 6,000+ blocks apart. I tried using `npm run range`, but it'll take some time to process all the transactions in each block.

Would it be possible to pass in an ordered list of transactions to test. For example:
```bash
$ npm run --tx  HASH_A,HASH_B,HASH_C
```

**Comment by haseebrabbani** [comment]
absolutely! this is supported as of v0.0.33. example usage: `npm run tx A,B,C`

**Comment by mwakaba2** [comment]
sweet! thanks @haseebrabbani, I was able to test several transactions!
