### ISSUE TITLE
Deprecate or remove receipt from docs/sdk

### ISSUE THREAD

**Issue by stevenlanders** [forta-protocol/forta-agent-sdk#122]
- Receipt should be removed from transaction event (it's available on protocol, but only because it's backfilled for compatibility)
- If an agent wants the receipt, they can get it via web3 lookup (eth_getTransactionReceipt) - and should consider filtering by something else first (e.g., topic / address) so that they don't hit a rate limit

**Comment by haseebrabbani** [comment]
this is on my radar, planning to have it done by end of week

**Comment by haseebrabbani** [comment]
implemented in https://github.com/forta-protocol/forta-agent-sdk/commit/8253df9708ef2d8a220ca72cbe3490458f8021c8
published in v0.1
