### ISSUE TITLE
Update Forta Terms of Use URL

### ISSUE THREAD

**Issue by echoAE** [forta-protocol/forta-agent-sdk#128]
https://github.com/forta-protocol/forta-agent-sdk/blob/e400a70d384e0d710a421a0a804d589219db7127/cli/commands/init/index.ts#L84

```suggestion
console.log(`You agree that your use is subject to the terms and conditions found at https://forta.org/legal/`)
```

**Comment by haseebrabbani** [comment]
fixed in https://github.com/forta-protocol/forta-agent-sdk/commit/25814fe1baa8a29e220ed171b7a1d002a6bf2de6
published in v0.1
